### ISSUE TITLE
issue while upgrading adf 2.4 to 2.5 

### ISSUE THREAD

**Issue by sai401** [Alfresco/alfresco-ng2-components#4014]
**Type of issue:**  (check with "[x]")

> - [x] Support request

**Current behaviour:**
 Not opening application after upgrade identified console errors

**Expected behavior:**
 application should open default home page after build success 

`Can't resolve all parameters for LoginComponent: (?, ?).
    at syntaxError (compiler.js:1016)
    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getDependenciesMetadata (compiler.js:10917)
    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getTypeMetadata (compiler.js:10810)
    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNonNormalizedDirectiveMetadata (compiler.js:10429)
    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getEntryComponentMetadata (compiler.js:11013)
    at compiler.js:11004
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getEntryComponentsFromProvider (compiler.js:11003)
    at compiler.js:10976
    at Array.forEach (<anonymous>)`

**Comment by eromano** [comment]
can you please provide an example app?

**Comment by sai401** [comment]
I have made fresh code started updating all worked well and some issues found after login 
1 Some console errors seen while inspect to browser, those need to fix in order to work left side filter.
2 Filter not working and keeps loading unable see filter on left side need to work on it
3 Some Extra empty cards seen in every page where ever we use gallery documentlist cards 
These are the issues identified by me after upgrade . and about 1,2,3 issues i am uploading in this comment , please check in attachments.
![11](https://user-images.githubusercontent.com/20453732/49237673-bbb4fa00-f424-11e8-9e44-0486157050d0.png)
![22](https://user-images.githubusercontent.com/20453732/49237675-bbb4fa00-f424-11e8-99d9-caa545b9c076.png)
![33](https://user-images.githubusercontent.com/20453732/49237677-bbb4fa00-f424-11e8-85b5-69498ca23365.png)

**Comment by eromano** [comment]
@sai401 the empty row are normal is a trick that is needed for the flex layout and have the table ordered you should not add a border on those hided

For the expression changed error this is a common error in angular that is probably in your code please give a look here:

https://blog.angularindepth.com/everything-you-need-to-know-about-the-expressionchangedafterithasbeencheckederror-error-e3fd9ce7dbb4

you can download the demo shell and execute it. You will notice that in the document list we don't have this error. Please if you see something different let me know how to reproduce it in the demo shell

**Comment by sai401** [comment]
After updating to adf 2.4 to 2.5 , I am getting those errors , i have used expanded property in 2.4 but in 2.5 property is not there in 2.5
ERROR in src/app/components/assets-filter/assets-filter.component.ts(91,15): error TS2339: Property 'expanded' does not exist on type 'FacetField'.
src/app/components/assets-filter/assets-filter.component.ts(95,15): error TS2339: Property 'expanded' does not exist on type 'FacetField'.
src/app/components/assets-filter/assets-filter.component.ts(214,40): error TS2339: Property 'expanded' does not exist on type 'FacetField'.
onFacetFieldExpanded(field: FacetField) { field.expanded = true; } onFacetFieldCollapsed(field: FacetField) { field.expanded = false; }

**Comment by eromano** [comment]
@sai401 can you try last version 2.6.1 ?

**Comment by sai401** [comment]
is there select all checkbox for adf-document-list in gallery view also in adf 2.4. Currently for gallery view select all check box is not having. or any event i have to fire from my component

**Comment by sai401** [comment]
> @sai401 the empty row are normal is a trick that is needed for the flex layout and have the table ordered you should not add a border on those hided
> 
> For the expression changed error this is a common error in angular that is probably in your code please give a look here:
> 
> https://blog.angularindepth.com/everything-you-need-to-know-about-the-expressionchangedafterithasbeencheckederror-error-e3fd9ce7dbb4
> 
> you can download the demo shell and execute it. You will notice that in the document list we don't have this error. Please if you see something different let me know how to reproduce it in the demo shell

Thank you for support
